#! /bin/sh

LOCKFILE=/run/image.lock
HOOK_PRE=true
HOOK_POST=true
TIMEOUT=600
HUNKPROG=/usr/bin/apply-stream-hunk
STREAMDECODE_OPTS="--min-strength 10"
AUTOREBOOT_BLOCKDEV='/sbin/reboot -f'
NOTIFY_PORT=6666

. /etc/elito-rescue.conf

DEV=${1:-mmcblk0p1}
NAME=${2:-image.stream}

PROG="try-blockdevice[$DEV]"
. /usr/share/elito-rescue/functions

mount -o ro /dev/"$DEV" /mnt 2>/dev/null >/dev/null || \
    panic "failed to mount $DEV"

f=/mnt/$NAME

if test -e "$f"; then
    tmpdir=`mktemp -d /tmp/tcp-stream.XXXXXX` || panic "Failed to create tmpdir"
    trap "rm -rf $tmpdir" EXIT

    log_info "found $f"
    (
      umount -l /mnt

      flock -n 250 || panic "Image update already active"

      $HOOK_PRE

      cd $tmpdir || panic "Failed to changed into tmpdir"
      cat | /usr/bin/elito-stream-decode \
          ${NOTIFY_PORT:+--notify-port "$NOTIFY_PORT"} \
	  --execute "$HUNKPROG"  \
	  $STREAMDECODE_OPTS
    ) 250>$LOCKFILE <"$f" || panic "Image update failed"

    sync

    $HOOK_POST

    exec $AUTOREBOOT_BLOCKDEV
fi

umount /mnt
