#! /bin/sh

log_debug() {
    logger -t 'apply-stream-hunk' -p debug "$*"
}

log_info() {
    echo -n "$*"
    logger -t "$PROG" -p info "$*"
}

log_error() {
    echo "$*" >&2
    logger -t "$PROG" -p error "$*"
}

log_success() {
    echo "${1:- ok}"
}

panic() {
    log_error "$*"
    ${HOOK_PANIC:-:}
    exit 1
}

wait_ok() {
    echo -n "$1"
    if tty 2>/dev/null >/dev/null; then
	read
    else
	REPLY=${2:-yes}
	echo "$REPLY (implied)"
    fi

    case $REPLY in
      [yY]*) ;;
      *)    echo "aborting..."; exit 0
    esac
}
