#! /bin/sh

LOCKFILE=/var/lock/image.lock
HOOK_PRE=true
HOOK_POST=true
TIMEOUT=600
HUNKPROG=/usr/bin/apply-stream-hunk
STREAMDECODE_OPTS="--min-strength 10"
AUTOREBOOT_TCP=false

. /etc/elito-rescue.conf

PROG="tcp-stream"
. /usr/share/elito-rescue/functions


f=`mktemp -d /tmp/tcp-stream.XXXXXX` || panic "Failed to create tmpdir"
trap "rm -rf $f" EXIT

set -e

exec 250>$LOCKFILE
flock -n 250 || panic "Image update already active"

echo -n "Receiving data..."

$HOOK_PRE

cd "$f"
{ timeout -t $TIMEOUT cat || panic "Timeout while receiving stream"; } | \
    /usr/bin/elito-stream-decode \
	  --execute "$HUNKPROG"  \
	  $STREAMDECODE_OPTS 2>&1 \
    || panic "Failed to apply stream"
echo " done"

$HOOK_POST

! $AUTOREBOOT_TCP || exec /sbin/reboot -f
