#! /bin/sh

LOCKFILE=/run/image.lock
HOOK_PRE=true
HOOK_POST=true
TIMEOUT=600
HUNKPROG=/usr/bin/apply-stream-hunk
STREAMDECODE_OPTS="--min-strength 10"
#AUTOREBOOT_TCP='/sbin/reboot -f'
AUTOREBOOT_TCP='/bin/true'
NOTIFY_PORT=6666

. /etc/elito-rescue.conf

PROG="tcp-stream"
. /usr/share/elito-rescue/functions


f=`mktemp -d /tmp/tcp-stream.XXXXXX` || panic "Failed to create tmpdir"
trap "rm -rf $f" EXIT

set -e

exec 250>$LOCKFILE
flock -n 250 || panic "Image update already active"

echo -n "Receiving data..."

$HOOK_PRE

cd "$f"
{ timeout -t $TIMEOUT cat || panic "Timeout while receiving stream; ret $?"; } | { \
    /usr/bin/elito-stream-decode \
        ${NOTIFY_PORT:+--notify-port "$NOTIFY_PORT"} \
	--execute "$HUNKPROG"  \
	$STREAMDECODE_OPTS 2>&1 \
	|| panic "Failed to apply stream; ret $?"
}
echo " done"

$HOOK_POST

# close file descriptor
exec 0<&-
exec 1>&-

exec $AUTOREBOOT_TCP
